import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.tsx",
    "src/gauge-chart.tsx",
    "src/line-chart.tsx",
    "src/fan-chart.tsx",
    "src/area-chart.tsx",
    "src/scatter-chart.tsx",
    "src/range-chart.tsx",
    "src/ribbon-chart.tsx",
    "src/radar-chart.tsx",
    "src/vertical-stack-bar-chart.tsx",
    "src/comparable-horizontal-bar-chart.tsx",
    "src/comparable-vertical-bar-chart.tsx",
    "src/dual-horizontal-bar-chart.tsx",
    "src/bar-bell-chart.tsx",
    "src/gap-chart.tsx",
    "src/treemap-chart.tsx",
    "src/pie-chart.tsx",
    "src/bubble-chart.tsx",
    "src/sankey-chart.tsx",
    "src/fountain-chart.tsx",
    "src/choropleth-map-chart.tsx",
    "src/symbol-map-chart.tsx",
    "src/radial-tree-chart.tsx",
  ],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: true,
});
